<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <RootNamespace>Offgrid.Portal.Customers.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DomainEvents\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../libs/dotnet/src/Offgrid.Framework/Offgrid.Framework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudNative.CloudEvents" Version="2.8.0" />
  </ItemGroup>

</Project>