@base_url={{$dotenv SHOP_API_BASE_URL}}
@client_id={{$dotenv OG_KC_CLIENT_ID}}
@client_secret={{$dotenv OG_KC_CLIENT_SECRET}}

# Select the user to authenticate as a Standard Customer, Silver Customer, or Gold Customer:
@username={{$dotenv OG_KC_CUSTOMER_STANDARD_USERNAME}}
@password={{$dotenv OG_KC_CUSTOMER_STANDARD_PASSWORD}}
# @username={{$dotenv OG_KC_CUSTOMER_SILVER_USERNAME}}
# @password={{$dotenv OG_KC_CUSTOMER_SILVER_PASSWORD}}
# @username={{$dotenv OG_KC_CUSTOMER_GOLD_USERNAME}}
# @password={{$dotenv OG_KC_CUSTOMER_GOLD_PASSWORD}}

@realm={{$dotenv OG_KC_REALM}}
@token_url={{$dotenv OG_KC_BASE_URL}}/realms/{{realm}}/protocol/openid-connect/token


###  1. Password Grant (Resource Owner Password Credentials)
# @name login

POST {{token_url}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&password={{password}}
&username={{username}}
&client_id={{client_id}}
&client_secret={{client_secret}}


###
@access_token={{login.response.body.access_token}}


### Upsert Customer - Invalid data with empty body
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}


### Upsert Customer - Invalid data with missing fields
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}
{}


### Upsert Customer - Invalid data with empty strings
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "keycloakUserId": "",
  "fullName": "",
  "email": ""
}


### Upsert Customer - Invalid data with values that violate data annotation validations
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}
{
"keycloakUserId": "x",
"fullName": "x",
"email": "x"
}


### Upsert Customer - Invalid data with missing last name (in fullname)
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}
{
"keycloakUserId": "d290f1ee-6c54-4b01-90e6-d701748f0851",
"fullName": "Jonny",
"email": "john.doe@example.com"
}


### Upsert Customer - Invalid data with inconsistent case
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "keycloakUserId": "d290f1ee-6c54-4b01-90e6-d701748f0851",
  "fullName": "joHn doE",
  "email": "joHN.doE@examPLe.com"
}


### Upsert Customer - Invalid data with extra spaces
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "keycloakUserId": "   d290f1ee-6c54-4b01-90e6-d701748f0851   ",
  "fullName": "      John    Doe     Doe    ",
  "email": "    john.doe@example.com"
}


### Upsert Customer - Valid Data
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "keycloakUserId": "d290f1ee-6c54-4b01-90e6-d701748f0851",
  "fullName": "John Doe",
  "email": "john.doe@example.com"
}