name: offgrid-stack

networks:
  default:
    name: offgrid

include:
  - ./postgres/compose.yaml
  - ./keycloak/compose.yaml
  - ./rabbitmq/compose.yaml
  - ./mongo/compose.yaml
  - ./typesense/compose.yaml
