services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: offgrid_rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_ERLANG_COOKIE: cookie_for_clustering
      RABBITMQ_DEFAULT_USER: ${OG_RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${OG_RABBITMQ_DEFAULT_PASS}
    networks:
      - default
    volumes:
      - rabbitmq-etc:/etc/rabbitmq/
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
volumes:
  rabbitmq-etc:
  rabbitmq-data:
  rabbitmq-logs:
